name: Build Godot Project

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main

jobs:
  Build and test the exe:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Godot
      uses: josephbmanley/godot-export@v1
      with:
        godot-version: '4.3.1'

    - name: Build for Windows
      run: godot --path ./a_party_game_with_tower --export "Windows Desktop" ./a_party_game_with_tower/TowerParty_win.exe

    - name: Tests 
